name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  GCP_SIGNER_PROJECT: ${{secrets.GCP_SIGNER_PROJECT}}
  GCP_SIGNER_LOCATION: ${{secrets.GCP_SIGNER_LOCATION}}
  GCP_SIGNER_KEY_RING: ${{secrets.GCP_SIGNER_KEY_RING}}
  GCP_SIGNER_KEY: ${{secrets.GCP_SIGNER_KEY}}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        go: [ '1.17.x', '1.16.x' ]
    name: "Test [ Go ${{ matrix.go }} ]"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0.4.4
        with:
          create_credentials_file: true
          workload_identity_provider: projects/923769985680/locations/global/workloadIdentityPools/github-actions/providers/jwx-go
          service_account: github-actions@go-jwx.iam.gserviceaccount.com
      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Install Go stable version
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: |
          env | sort
          go env | sort
          cd gcp
          go test 
 

